### ISSUE TITLE
Query returning nested properties fails to resolve with proper response.

### ISSUE THREAD

**Issue by isaiahdahl** [DustinJSilk/qwik-urql#28]
Works:
```
query Projects($title: String!) {
  Projects(where: {title: {like: $title}} ) {
    docs {
      id
      title
    }
  }
} 
```
![CleanShot 2022-11-04 at 16 01 23](https://user-images.githubusercontent.com/23046374/200086822-cbd43785-7ba8-470b-9547-f5ad1e7645bd.png)

Doesn't Work:
```
query Projects($title: String!) {
  Projects(where: {title: {like: $title}} ) {
    docs {
      id
      title
    }
    meta {
      title
      description
    }
  }
} 
```
![CleanShot 2022-11-04 at 16 00 39](https://user-images.githubusercontent.com/23046374/200086770-2ad554a3-aeac-434d-b875-a09893062948.png)

Even though it's not working on site, the query is actually returning the proper data from the API. It's just not resolving correctly.

**Comment by DustinJSilk** [comment]
Thanks for reporting @isaiahdahl, I'll take a look at this today

**Comment by DustinJSilk** [comment]
Feel free to open a new issue with a reproduction link
