### ISSUE TITLE
slow queries are blocking the server reply

### ISSUE THREAD

**Issue by bbigras** [DustinJSilk/qwik-urql#31]
Not sure how to phrase this.

To test, I added a 5 secs sleep in my GraphQL backend.

Now, with `npm run preview`, nothing is rendered for the first 5 seconds.

I'm still very new to qwik. Is it normal that the whole rendering is blocked, or should only the specific `Resource` be?

**Comment by DustinJSilk** [comment]
This will be fixed in the next release with https://github.com/DustinJSilk/qwik-urql/pull/16

Currently waiting for a new release on Qwik that fixes this error https://github.com/BuilderIO/qwik/pull/1985

Thanks for the report and patience!

**Comment by bbigras** [comment]
Do you think I could test #16 by doing a checkout of qwik and qwik-urql, `yarn build` them and pointing my code to them?

I tried, but I didn't see any improvement.

**Comment by DustinJSilk** [comment]
A new release is out, could you give it a go and if you're still having issues a link to reproduce it would be helpful

**Comment by bbigras** [comment]
https://github.com/bbigras/qwik-urql/tree/slow-queries

```sh
yarn run preview

# will take 5 seconds
time curl --silent --output /dev/null http://localhost:4173/slow
```

Note that I might not have explained my problem correctly, and I might have been assuming that qwik would determine, somehow, that the query is taking too long and then chose to render it on the client instead of the server.

So basically, I'm wondering how to make my example not take 5 seconds. Maybe there's a way to force the fetch on the client side.

Also, sorry I had to make all those probably useless changes to make my code run.

My example is basically just:

https://github.com/bbigras/qwik-urql/blob/4dcfbdbe23373328295d00f1c7b8af8c133f898d/src/example/routes/slow/index.tsx#L1-L21

and

https://github.com/bbigras/qwik-urql/blob/4dcfbdbe23373328295d00f1c7b8af8c133f898d/src/example/api.ts#L34-L40

**Comment by DustinJSilk** [comment]
Right I see. The difficulty lies with Qwiks Resource component. Unfortunately there’s no way for qwik to stop loading on the server and resume on the client for long queries. We can add a timeout which I believe both qwik and Urql support, but that would basically make the query error.

You’ll need to chose which queries you want fetched on the server and which ones you want forced to only be fetched on the client.

To make a client only query, try and follow the documentation about using resources without the Resource component. You’d then need to trigger it with a useClientEffect$ with eagerness set to ‘load’.

https://qwik.builder.io/docs/components/resource/ 

I won’t be able to give this a try myself for a few days but I’m happy to help here where I can

**Comment by bbigras** [comment]
Nice, it seems to be working well. Thank you very much :smiley: 

I'm not sure how to prevent the query from running on the server, though. Is there something like `pause`?

For now, it's not a huge deal since the query just fails quickly with `null`, on the server side.

**Comment by DustinJSilk** [comment]
You could possibly wrap a Resource component with an if-statement and then show it on the client only. Something like this:

```tsx
export const MyComponent = component$(() => {
  const render = useSignal(false);
  const value = useQuery(MyQuery);

  useClientEffect$(() => {
    render.value = true;
  }, { eagerness: ‘load’ })

  return <div>
    { render && <Resource value={value} … /> }
    { !render && <div>loading…</div>
  </div>
```

**Comment by DustinJSilk** [comment]
Closing this now as it seems to not be an issue any more.
