### ISSUE TITLE
Optional/nullable fields make the whole query not render

### ISSUE THREAD

**Issue by edwinvdgraaf** [DustinJSilk/qwik-urql#52]
Hi! 👋 

I've ran into an issue with optional/nullable fields and I have created a reproducible branch: https://github.com/edwinvdgraaf/qwik-urql/tree/fix-option-fields with a very naive solution. Thanks for the work you've done so far, if it would help I can create a PR out of this. But I'd like some guidance if that would a) help you and b) setting up testing around the `qwikExchange` class.

**Comment by DustinJSilk** [comment]
Hey @edwinvdgraaf 
Thanks for reporting! 

If you're up for adding a PR that would be awesome, otherwise I can take a look at this in the next day or 2 and add a few tests.

**Comment by DustinJSilk** [comment]
@edwinvdgraaf this is fixed and released in v0.4.1.
I've added a few tests to the exchange. If you come up with any more issues feel free to add an issue or a PR with some more test cases!

**Comment by edwinvdgraaf** [comment]
You're quick! Thanks for adressing this!
