### ISSUE TITLE
please-use-pnpm

### ISSUE THREAD

**Issue by bbigras** [DustinJSilk/qwik-urql#55]
Any reason we need to use pnpm to use qwik-urql?

With pnpm I have problems using other js libs.

**Comment by DustinJSilk** [comment]
Only that Qwik switched to pnpm and this was to stay in line.

What problem does it cause? I can remove that restriction if there’s no way around it

**Comment by bbigras** [comment]
I'll try to get the exact error, but I'm using `next-auth` like in https://github.com/wmalarski/qwik-next-auth-example and with pnpm, I get errors about missing next and react IIRC. but not with npm.

**Comment by DustinJSilk** [comment]
These restrictions have been removed in v0.4.2

**Comment by bbigras** [comment]
Thank you very much!
